Fix http.ex using module attributes for values not known at compile
aguxez/godfist pull request #2
Opened 2017-08-26 06:11 UTC by hankditton

2017-08-27 16:01 UTC, aguxez requested changes
Thank you for the PR!, however, before this gets merged I'd like to propose some changes to erase some warnings regarding new function names without parentheses.

2017-08-27 16:01 UTC, aguxez commented on lib/godfist/http.ex
> +    |> ExRated.check_rate(time, amount)
`time` and `amount` are function names.

2017-08-27 16:01 UTC, aguxez commented on lib/godfist/http.ex
> +        get_body("#{url <> rest}&api_key=#{token}")
`token` is a function name

2017-08-27 16:01 UTC, aguxez commented on lib/godfist/http.ex
> +        get_body("#{url <> rest}?api_key=#{token}")
`token` is a function name

2017-08-28 01:29 UTC, aguxez approved these changes

2017-08-28 01:29 UTC, merged

2017-08-28 01:30 UTC, hankditton commented
Sorry, total elixir noob here. Thanks for catching that.